### ISSUE TITLE
Missing now/next(blue) in neutrino2 channellist

### ISSUE THREAD

**Issue by wolfgangmauer** [mohousch/buildsystem#10]
Missing now/next(blue) in neutrino2 channellist
Any setting to enable this?

**Comment by mohousch** [comment]
Hi

on the right side of the channellist there is a short information for now / next desciption

**Comment by wolfgangmauer** [comment]
Yes i know, i miss now/next in openatv thats the reason i switch to neutrino

**Comment by mohousch** [comment]
60dc19b88b5f73b3f2b2a0ee262cf1e2310d0dd8

if you want to test update neutrino2 sources
make neutrino2-distclean
make release-neutrino2

copy/paste neutrino2 bin from release/usr/bin to your box
dont forget to copy also to locales

if you want to build new image you need first 
make neutrino2-distclean

Happy zapping
