### ISSUE TITLE
gbue4k not starting neutrino/neutrino2

### ISSUE THREAD

**Issue by wolfgangmauer** [mohousch/buildsystem#9]
Some drivers/modules are missing ?

gbue4k:~# neutrino
[ca_ci] -> GetInstance
[ca_ci] -> cCA 1
no choices for input0
no choices for input1
no choices for input2
no choices for input3
[HAL:00000000:init  ] [CEC] new instance created 
failed to open /dev/ci0 ->No such file or directory>>> Neutrino (compiled Aug 16 2024 13:36:56) <<<
libstb-hal debug options can be set by exporting HAL_DEBUG.
The following values (or bitwise OR combinations) are valid:
        component: audio   0x01
        component: video   0x02
        component: demux   0x04
        component: play    0x08
        component: power   0x10
        component: init    0x20
        component: ca      0x40
        component: record  0x80
        all components:    0xff
[HAL:00000000:init  ] hal_api_init begin, initialized=0, debug=0x00
[HAL:00000000:init  ] hal_api_init end
[fb_accel_arm] [bcm] /dev/fb0 No such file or directory[fb_accel_arm] [bcm] interface not available - No such file or directory[fb_accel_arm] run start
[neutrino] armbox framebuffer Instance created
/dev/fb0: No such file or directory
framebuffer not available.
[ConfigFile] Unable to open file /var/tuxbox/config/neutrino.conf for reading.
[fb_accel_arm] FBIOPUT_VSCREENINFO: Bad file descriptor
[fb_accel_arm] SetMode: 32bits, red 0:0 green 0:0 blue 0:0 transp 0:0
[fb_accel_arm] FBIOGET_FSCREENINFO: Bad file descriptor
[neutrino] Error while setting framebuffer mode

**Comment by wolfgangmauer** [comment]
rc_Neutrino/rc_Neutrino2 dvb_init ......  kernel path is wrong ;-)

**Comment by mohousch** [comment]
Yes that was the issue 
and now after fixing it doea still don't start?
I don't have this box cant test

**Comment by wolfgangmauer** [comment]
Unfortunately not, after flashing there is an infinite boot/reboot loop

**Comment by wolfgangmauer** [comment]
neutrino doesn't start because ntpdate doesn't exist
